### ISSUE TITLE
Consider swapping generateToken parameter order

### ISSUE THREAD

**Issue by mattfiocca** [Psifi-Solutions/csrf-csrf#12]
Hello!

I just wanted to point out that in the example at `https://github.com/Psifi-Solutions/csrf-csrf/blob/main/example/complete/src/index.js`, line 53:

`token: generateToken(res,req),`

should be:

`token: generateToken(req,res),`

The request and response objects appear to be swapped...

**Comment by psibean** [comment]
The example is correct and works.

If we look at the `generateToken` here in the double csrf code:

https://github.com/Psifi-Solutions/csrf-csrf/blob/main/src/index.ts#L103

We can see that `generateToken` does take the response first, followed by the request.

However, it's true that these should probably be swapped around for consistency, but this isn't a big issue and would likely be best to be part of the next major version release, as it would be a breaking change. But it does work as is, and expects the response to be passed in first.

**Comment by mattfiocca** [comment]
Ah yes, you are correct. I am wrapping this in a module and had it reversed at the outset, making it look like it needed reversing at `generateToken`.

Nice work on this, btw

**Comment by psibean** [comment]
Version 4.0.1 exposes `generateToken` via `req.csrfToken` now, similar to how `csurf` did it previously.

This means you can do:

`req.csrfToken()` to generate a new token instead, and there is no need to import `generateToken`, and no need to remember the res/req parameter order!

**Comment by psibean** [comment]
I'm going to close this issue for now, but if anyone still has a problem with this, please comment! Why am I closing this?

* Given that the `req.csrfToken()` option is now available, the parameter order for generateToken is no longer relevant!
* Changing the parameter order would be a breaking change, requiring a major version update. There are no other breaking changes being made in the foreseeable future. This change may be reconsidered if other breaking changes need to be made.
