### ISSUE TITLE
The TypeScript compiler is unable to recognize the extended Request interface, specifically the csrfToken method.

### ISSUE THREAD

**Issue by bkvishe** [Psifi-Solutions/csrf-csrf#51]
# Description:
I am experiencing an issue with the TypeScript environment. The TypeScript compiler is unable to recognize the extended Request interface provided by the `csrf-csrf` package, specifically the `csrfToken` method.

<img width="769" alt="image" src="https://github.com/Psifi-Solutions/csrf-csrf/assets/9004722/10cff991-38ef-4b84-a66d-791c473c2574">

# Environment:

- `csrf-csrf` package version: 3.0.3
- TypeScript version: 4.6.4
- Node.js version: 18.17.1
- Express.js version: 4.18.1

# Steps to Reproduce:

1. Install `csrf-csrf` and set it up as middleware in an Express.js application.
2. Attempt to use `req.csrfToken()` in a TypeScript file.
3. Observe TypeScript compiler error indicating that `req.csrfToken` might be undefined.

# Attempted Solutions:

1. Checked import paths and package versions for compatibility.
2. Tried clearing npm and Yarn cache and reinstalling packages.

**Comment by psibean** [comment]
Interesting, your tsconfig has `node_modules` configured for type detection?

**Comment by bkvishe** [comment]
I used `non-null assertion operator` and it worked!

I appreciate your guidance on this matter and agree that while the `non-null assertion operator` works, it's a workaround rather than a solution to the fundamental issue of TypeScript's static analysis limitations regarding middleware. If there are any plans to update the type definitions to handle this scenario more elegantly, or if you have any recommended practices for such cases, I'd be interested to learn more.

**Comment by psibean** [comment]
> I appreciate your guidance on this matter and agree that while the `non-null assertion operator` works, it's a workaround rather than a solution to the fundamental issue of TypeScript's static analysis limitations regarding middleware. If there are any plans to update the type definitions to handle this scenario more elegantly, or if you have any recommended practices for such cases, I'd be interested to learn more.

Yeah, I think it might be ideal to change the type for now. The documentation already states that it can only be used _after_ the middleware has executed anyways. Will try to do it this week.

**Comment by psibean** [comment]
Thoughts on this one @davidgonmar ? I think it's more accurate to keep the type as potentially undefined and users should use type checking and optional chaining to ensure it is. Users should be ensuring they're calling it only after the middleware has executed.

On the other hand, if you do something like `req.csrfToken?.(true)` and then it doesn't generate a token, but you're expecting it to have overwritten, what's going to happen? Would it be better to just allow `req.csrfToken(true)` without the type safety and have it error at runtime?

**Comment by davidgonmar** [comment]
Another weird way could be having a `enable-request-csrftoken.ts` file (or whatever name), do the declaration (and binding, somehow) there, so the user has to explicitly import that file for the request to have it. But I am not sure if it is even worth it. I don't think there are other alternatives other than that, leaving it with the ?, or just doing req.csrfToken(...).

**Comment by psibean** [comment]
I've come back and reviewed the discussion here and I still feel that having `csrfToken` as possibly undefined on the request object is the correct approach. It should be up to the user to enforce the presence of `csrfToken` at the correct times. Almost all examples out there of extending the Request object with your own properties have it marked as `?` potentially undefined.
