### ISSUE TITLE
How to change the error message returned?

### ISSUE THREAD

**Issue by chr15m** [Psifi-Solutions/csrf-csrf#55]
I would like to change the error message that is returned when a 403 is triggered due to a CSRF error. At the moment it is "invalid csrf token". I would like to add more information for the developer and instructions on how they can fix the issue, such as a link to my documentation. Is there a way to modify the error message without writing my own middleware?

**Comment by psibean** [comment]
Yeah, this has been a problem for a while now.

Definitely need to update the config with an `errorMessage` string that defaults to the current one. Initially I was just making it a swap in for `csurf` - which didn't allow the error to be changed, and that was my initial reference point (along with other CSRF protection implementations).

Alternatively, you can also register your own error middleware handler and handle the error on the backend and return any kind of response you like. `csrf-csrf` doesn't return a response, it throws the error, and that is handled by the default express error handler, or by your own, see: https://expressjs.com/en/guide/error-handling.html

But that shouldn't be necessary just to change the message, it's just another alternative / workaround to having to rebuild the CSRF middleware

**Comment by psibean** [comment]
So a fix for this has been merged, I'll do a minor release within the next 8 hours and close this issue once it's published

**Comment by psibean** [comment]
Fixed and released with 3.0.4
