### ISSUE TITLE
3.0.6 version in npm?

### ISSUE THREAD

**Issue by seancolyer** [Psifi-Solutions/csrf-csrf#66]
It looks like latest code in the repo is 3.0.4, and changelog reflects that as well. [npm](https://www.npmjs.com/package/csrf-csrf/v/3.0.6?activeTab=code) has package.json with 3.0.6 and potentially other changes (haven't done a deep dive).

Do you know what's going on?

**Comment by psibean** [comment]
Yes.

I fucked up a bit with the TypeScript side of things with version 3.0.4, this means 3.0.4 types are broken, I also fucked up the 3.0.5 attempt to fix it. 🤦🏻 

As a result, I created a `v3.x.x` branch, which has the 3.0.5 & 3.0.6 changes.

The eventual plan is to have a workflow branching strategy such that supported versions will automatically open upstream PR's to have master updated with changes that target previous versions.

However, currently, the build using `tsup` is still broken in both `3.0.6` - I had to make some manually tweaks to the build output to make it work (for now). It's absolutely insane how bad the TypeScript compilation is, even with tsup, it just doesn't work as intended at all and it's infuriating.

So 3.0.6 is the version you should be using, find it at the v3.x.x branch.

Once I fix the compilation and wire up the branching, master will eventually catch up.

Going forward I plan to use vx.x.x branches for each version, and master will remain as a "next major" branch.
So once v4 releases, it'll be running off v4.x.x, I'll be sure to have the README updated to reflect this as well once it's ready.

**Comment by psibean** [comment]
I've set things up a bit better and I'll make sure fixes / changes to `v3.x.x` get merged up to master.

**Comment by seancolyer** [comment]
> I've set things up a bit better and I'll make sure fixes / changes to v3.x.x get merged up to master.

Thanks for getting this sorted out!
