### ISSUE TITLE
Issue with latest build

### ISSUE THREAD

**Issue by khaleddrashadd** [Psifi-Solutions/csrf-csrf#74]
Types file not exist in latest build which causes an error 

![image](https://github.com/user-attachments/assets/fc9c8f6c-fdfb-402e-b08b-be787e0d9842)
![image](https://github.com/user-attachments/assets/5287ab2c-8b77-4b50-b124-a06b63ef50e4)

**Comment by psibean** [comment]
Ugh. For fuck sake. I thought I fixed this. I don't know what's happening with this issue coming back constantly.

**Comment by psibean** [comment]
Fixed with 3.0.8 🤦🏻
