### ISSUE TITLE
CSRF between two backends

### ISSUE THREAD

**Issue by Nickk4** [Psifi-Solutions/csrf-csrf#78]
I've got csrf-csrf working for requests between a Node application and a React front-end.
But there's a second Node back-end that also needs to call on the first Node back-end. Since there's no front-end involved there, I add the csrf values manually to the request header and cookies.

No problem as far as the cookie is concerned. I request a csrf token and include both a regular and hashed version in the cookie. But the header is giving me a headache. Although it works locally, it does not in production.

I'd like to ask about the naming convention for the header. I've named the csrf cookie `__Secure-my.x-csrf-token`. Should that then also be the name of my header with the csrf token? Or should the header's name still be the default `x-csrf-token`? 

You might say: what a dumb question, if you've named it `__Secure-my.x-csrf-token` then the header should also take that name. But if the header has that name the nginx-ingress load balancer filters out the header. More importantly, if I look at requests between the React and Node application (where everything works, also in production), the header is sometimes absent and sometimes called `x-csrf-token` but never is the header's name in my logs `__Secure-my.x-csrf-token` even though the cookie name is `__Secure-my.x-csrf-token`.

Pointers how to get this to work are very welcome. There's little debugging feedback from the library when it returns false. There's no debugging mode, right?

**Comment by psibean** [comment]
You don't need CSRF protection when requesting between backends, CSRF is a browser based vulnerability, so requests being made between backends aren't susceptible to CSRF attacks.

The header by default will always be `x-csrf-token`, to change the header value you can configure the `getTokenFromRequest` to get the token from a different header name, this is why the header name isn't it's own config option as it's a bit redundant.

In saying that, `csrf-csrf` does not currently support an easy way for you to just ignore these B2B types of requests. You need to be careful and make sure you aren't skipping CSRF protection in a way that can be spoofed and abused for browser requests too.

**Comment by Nickk4** [comment]
Thank you @psibean , your answer is much appreciated! The silly thing is that skipping csrf for requests between backends was also how I started, but once an endpoint got involved that is also used by a front-end, I switched to manually add csrf to backend-to-backend requests. Now see that is the wrong way to go and will implement two endpoints for that one: one for the frontend and one for the backend to call upon. Thanks!

**Comment by psibean** [comment]
@Nickk4 what you need to realize is, simply having 2 endpoints isn't necessarily enough.

You need to ensure your backend only endpoint can only be reached by the things you intend to reach it.

That means if you open your browser and try to make a manual `fetch` request to your backend only API, then that should fail. You'll need to ensure to block all CORs on the backend endpoint, and you may wish to consider additional configuration too.

**Comment by Nickk4** [comment]
Thanks again @psibean! Yes, I now 1) skip csrf for those endpoints, 2) added the second backend as an allowed source to the CORS settings of the first backend, and 3) implemented an API key that the second backend needs to send along in the request body when talking to the first backend.
